### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by arblake** [ryu10/M5CardForth#1] opened 2023-12-30 18:57 UTC
Please explain as to how this may be installed on the M5Cardputer.

**Comment by ryu10** [comment] 2023-12-30 20:34
This repository is configured to work with PlatformIO IDE extension for MS Visual Studio Code. 
The outline of the installation steps will be:

1. Install MS Visual Studio Code ('VSCode') on your computer
2. In VSCode, install the PlatformIO IDE extension
3. Clone this repository on to your computer
4. Open the cloned repository in PlatformIO IDE
5. Connect the M5Cardputer to your computer
6. Click the Build/Upload buttons at the bottom of the PlatformIO IDE window.

You can find many resources on the web on how to install/use PlatformIO IDE. Please check them also.

If you come across any issues during the process, please let me know 1) the system (OS) that you use 2) how to reproduce the issue and 3) any system messages (errors, etc.) Thanks.

**Comment by arblake** [comment] 2023-12-31 07:28
Hi, It took a while to install the get started but success followed, so thanks. Where is the basic forth code? It would be good to allow to boot with m5key-on at boot time. 
I see that you are working to use the SD card.

**Comment by ryu10** [comment] 2023-12-31 08:04
Glad to hear that you successfully installed the software.

If you would like to look inside the code, I recommend to start with the vanilla Esp32forth. 
[https://esp32forth.appspot.com/ESP32forth.html](https://esp32forth.appspot.com/ESP32forth.html)

Since we are going off-topic, I will close this issue. 
Thanks.

**Closed as completed by ryu10** 2023-12-31 08:04 UTC

**Comment by lasamflir** [comment] 2024-04-23 08:43
Are you able to provide a .bin firmware file? I am totally unable to get PlatformIO to work, and this seems like a really cool firmware I'd love to try on my cardputer.
